apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crdloadtests.wlynch.dev
spec:
  group: wlynch.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        # One can use x-kubernetes-preserve-unknown-fields: true
        # at the root of the schema (and inside any properties, additionalProperties)
        # to get the traditional CRD behaviour that nothing is pruned, despite
        # setting spec.preserveUnknownProperties: false.
        #
        # See https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
        # See issue: https://github.com/knative/serving/issues/912
        x-kubernetes-preserve-unknown-fields: true
    # Opt into the status subresource so metadata.generation
    # starts to increment
    subresources:
      status: {}
  names:
    kind: CRDLoadtest
    plural: crdloadtests
  scope: Namespaced