/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/experimental/crd-loadtest/pkg/apis/wlynch.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCRDLoadtests implements CRDLoadtestInterface
type FakeCRDLoadtests struct {
	Fake *FakeWlynchV1alpha1
	ns   string
}

var crdloadtestsResource = schema.GroupVersionResource{Group: "wlynch.dev", Version: "v1alpha1", Resource: "crdloadtests"}

var crdloadtestsKind = schema.GroupVersionKind{Group: "wlynch.dev", Version: "v1alpha1", Kind: "CRDLoadtest"}

// Get takes name of the cRDLoadtest, and returns the corresponding cRDLoadtest object, and an error if there is any.
func (c *FakeCRDLoadtests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CRDLoadtest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(crdloadtestsResource, c.ns, name), &v1alpha1.CRDLoadtest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CRDLoadtest), err
}

// List takes label and field selectors, and returns the list of CRDLoadtests that match those selectors.
func (c *FakeCRDLoadtests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CRDLoadtestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(crdloadtestsResource, crdloadtestsKind, c.ns, opts), &v1alpha1.CRDLoadtestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CRDLoadtestList{ListMeta: obj.(*v1alpha1.CRDLoadtestList).ListMeta}
	for _, item := range obj.(*v1alpha1.CRDLoadtestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cRDLoadtests.
func (c *FakeCRDLoadtests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(crdloadtestsResource, c.ns, opts))

}

// Create takes the representation of a cRDLoadtest and creates it.  Returns the server's representation of the cRDLoadtest, and an error, if there is any.
func (c *FakeCRDLoadtests) Create(ctx context.Context, cRDLoadtest *v1alpha1.CRDLoadtest, opts v1.CreateOptions) (result *v1alpha1.CRDLoadtest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(crdloadtestsResource, c.ns, cRDLoadtest), &v1alpha1.CRDLoadtest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CRDLoadtest), err
}

// Update takes the representation of a cRDLoadtest and updates it. Returns the server's representation of the cRDLoadtest, and an error, if there is any.
func (c *FakeCRDLoadtests) Update(ctx context.Context, cRDLoadtest *v1alpha1.CRDLoadtest, opts v1.UpdateOptions) (result *v1alpha1.CRDLoadtest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(crdloadtestsResource, c.ns, cRDLoadtest), &v1alpha1.CRDLoadtest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CRDLoadtest), err
}

// Delete takes name of the cRDLoadtest and deletes it. Returns an error if one occurs.
func (c *FakeCRDLoadtests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(crdloadtestsResource, c.ns, name), &v1alpha1.CRDLoadtest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCRDLoadtests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(crdloadtestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CRDLoadtestList{})
	return err
}

// Patch applies the patch and returns the patched cRDLoadtest.
func (c *FakeCRDLoadtests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CRDLoadtest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(crdloadtestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CRDLoadtest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CRDLoadtest), err
}
