/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	wlynchdevv1alpha1 "github.com/tektoncd/experimental/crd-loadtest/pkg/apis/wlynch.dev/v1alpha1"
	versioned "github.com/tektoncd/experimental/crd-loadtest/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tektoncd/experimental/crd-loadtest/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tektoncd/experimental/crd-loadtest/pkg/client/listers/wlynch.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CRDLoadtestInformer provides access to a shared informer and lister for
// CRDLoadtests.
type CRDLoadtestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CRDLoadtestLister
}

type cRDLoadtestInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCRDLoadtestInformer constructs a new informer for CRDLoadtest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCRDLoadtestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCRDLoadtestInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCRDLoadtestInformer constructs a new informer for CRDLoadtest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCRDLoadtestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WlynchV1alpha1().CRDLoadtests(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WlynchV1alpha1().CRDLoadtests(namespace).Watch(context.TODO(), options)
			},
		},
		&wlynchdevv1alpha1.CRDLoadtest{},
		resyncPeriod,
		indexers,
	)
}

func (f *cRDLoadtestInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCRDLoadtestInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cRDLoadtestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&wlynchdevv1alpha1.CRDLoadtest{}, f.defaultInformer)
}

func (f *cRDLoadtestInformer) Lister() v1alpha1.CRDLoadtestLister {
	return v1alpha1.NewCRDLoadtestLister(f.Informer().GetIndexer())
}
