/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/tektoncd/experimental/crd-loadtest/pkg/apis/wlynch.dev/v1alpha1"
	scheme "github.com/tektoncd/experimental/crd-loadtest/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CRDLoadtestsGetter has a method to return a CRDLoadtestInterface.
// A group's client should implement this interface.
type CRDLoadtestsGetter interface {
	CRDLoadtests(namespace string) CRDLoadtestInterface
}

// CRDLoadtestInterface has methods to work with CRDLoadtest resources.
type CRDLoadtestInterface interface {
	Create(ctx context.Context, cRDLoadtest *v1alpha1.CRDLoadtest, opts v1.CreateOptions) (*v1alpha1.CRDLoadtest, error)
	Update(ctx context.Context, cRDLoadtest *v1alpha1.CRDLoadtest, opts v1.UpdateOptions) (*v1alpha1.CRDLoadtest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CRDLoadtest, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CRDLoadtestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CRDLoadtest, err error)
	CRDLoadtestExpansion
}

// cRDLoadtests implements CRDLoadtestInterface
type cRDLoadtests struct {
	client rest.Interface
	ns     string
}

// newCRDLoadtests returns a CRDLoadtests
func newCRDLoadtests(c *WlynchV1alpha1Client, namespace string) *cRDLoadtests {
	return &cRDLoadtests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cRDLoadtest, and returns the corresponding cRDLoadtest object, and an error if there is any.
func (c *cRDLoadtests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CRDLoadtest, err error) {
	result = &v1alpha1.CRDLoadtest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crdloadtests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CRDLoadtests that match those selectors.
func (c *cRDLoadtests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CRDLoadtestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CRDLoadtestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crdloadtests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cRDLoadtests.
func (c *cRDLoadtests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("crdloadtests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cRDLoadtest and creates it.  Returns the server's representation of the cRDLoadtest, and an error, if there is any.
func (c *cRDLoadtests) Create(ctx context.Context, cRDLoadtest *v1alpha1.CRDLoadtest, opts v1.CreateOptions) (result *v1alpha1.CRDLoadtest, err error) {
	result = &v1alpha1.CRDLoadtest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("crdloadtests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cRDLoadtest).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cRDLoadtest and updates it. Returns the server's representation of the cRDLoadtest, and an error, if there is any.
func (c *cRDLoadtests) Update(ctx context.Context, cRDLoadtest *v1alpha1.CRDLoadtest, opts v1.UpdateOptions) (result *v1alpha1.CRDLoadtest, err error) {
	result = &v1alpha1.CRDLoadtest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crdloadtests").
		Name(cRDLoadtest.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cRDLoadtest).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cRDLoadtest and deletes it. Returns an error if one occurs.
func (c *cRDLoadtests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crdloadtests").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cRDLoadtests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crdloadtests").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cRDLoadtest.
func (c *cRDLoadtests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CRDLoadtest, err error) {
	result = &v1alpha1.CRDLoadtest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("crdloadtests").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
